version: '3.3'

networks:
  csw_net:
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET}

services:
  # ========== CSW Services ==========
  seed:
    image: csw-cluster-seed:${TAG_ID}
    ports:
      - ${CLUSTER_PORT}:${CLUSTER_PORT}
      - ${LOCATION_SERVER_PORT}:${LOCATION_SERVER_PORT}
      - ${ADMIN_PORT}:${ADMIN_PORT}
    command:
      - "-DclusterSeeds=${SEED_IP}:${CLUSTER_PORT}"
      - "--clusterPort=${CLUSTER_PORT}"
    networks:
      csw_net:
        ipv4_address: ${SEED_IP}

  config:
    image: csw-config-server:${TAG_ID}
    ports:
      - ${CONFIG_PORT}:${CONFIG_PORT}
    command:
      - "-DclusterSeeds=${SEED_IP}:${CLUSTER_PORT}"
      - "--initRepo"
    networks:
      - csw_net
    depends_on:
      - seed

  location-agent:
    image: csw-location-agent:${TAG_ID}
    command:
      - "-DclusterSeeds=${SEED_IP}:${CLUSTER_PORT}"
      - "--name=EventServer,AlarmServer"
      - "--command=sleep 100000"
      - "--port=${SENTINEL_PORT}"
    networks:
      - csw_net
    depends_on:
      - sentinel

  # ========== Sentinel Setup ==========
  event_master:
    image: redis:latest
    ports:
      - ${EVENT_MASTER_PORT}:${EVENT_MASTER_PORT}
    command: ["redis-server", "--port", "${EVENT_MASTER_PORT}", "--notify-keyspace-events", "K$$x", "--protected-mode", "no"]
    networks:
      - csw_net

  event_slave:
    image: redis:latest
    ports:
      - ${EVENT_SLAVE_PORT}:${EVENT_SLAVE_PORT}
    command: ["redis-server", "--port", "${EVENT_SLAVE_PORT}", "--notify-keyspace-events", "K$$x", "--protected-mode", "no"]
    networks:
      - csw_net
    depends_on:
      - event_master

  alarm_master:
    image: redis:latest
    ports:
      - ${ALARM_MASTER_PORT}:${ALARM_MASTER_PORT}
    command: ["redis-server", "--port", "${ALARM_MASTER_PORT}", "--notify-keyspace-events", "K$$x", "--protected-mode", "no"]
    networks:
      - csw_net

  alarm_slave:
    image: redis:latest
    ports:
      - ${ALARM_SLAVE_PORT}:${ALARM_SLAVE_PORT}
    command: ["redis-server", "--port", "${ALARM_SLAVE_PORT}", "--notify-keyspace-events", "K$$x", "--protected-mode", "no"]
    networks:
      - csw_net
    depends_on:
      - alarm_master

  sentinel:
    image: redis:latest
    ports:
      - ${SENTINEL_PORT}:${SENTINEL_PORT}
    volumes:
      - "./scripts/conf:/data/conf"
    command: redis-sentinel /data/conf/redis_sentinel/sentinel.conf
    networks:
      - csw_net
    depends_on:
      - event_master
      - alarm_master
